### ISSUE TITLE
没有armeabi的库

### ISSUE THREAD

**Issue by zhonglikui** [Faceunity/FULiveDemoDroid#6]
由于项目中还有其他的第三方库文件，所以需要限定使用armeabi的库，但是demo里面没有

**Comment by AndroidInternal** [comment]
hi，用armeabi-v7a的即可

**Comment by zhonglikui** [comment]
在gradle里面有这样一句        ndk { abiFilters 'armeabi' }就是说只能用armeabi的，如果加上或换成armeabi-v7a其他的就会报错了！

**Comment by AndroidInternal** [comment]
将armeabi-v7a的so放至armeabi对应文件夹，不要改原来的abiFilters。

**Comment by zhonglikui** [comment]
现在有可以录制视频的demo了吗？我参考了Demo和Grafika里面的代码写录制功能写的代码出现了下面的错误
`  java.lang.RuntimeException: glUniformMatrix4fv: glError 0x502
                                                                       at com.prprlive.faceunity.gles.GlUtil.checkGlError(GlUtil.java:114)
                                                                       at com.prprlive.faceunity.gles.Texture2dProgram.draw(Texture2dProgram.java:291)
                                                                       at com.prprlive.faceunity.gles.FullFrameRect.drawFrame(FullFrameRect.java:86)
                                                                       at com.prprlive.faceunity.encoder.TextureMovieEncoder.handleFrameAvailable(TextureMovieEncoder.java:243)
                                                                       at com.prprlive.faceunity.encoder.TextureMovieEncoder.access$300(TextureMovieEncoder.java:64)
                                                                       at com.prprlive.faceunity.encoder.TextureMovieEncoder$VideoEncoderHandler.handleMessage(TextureMovieEncoder.java:431)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at com.prprlive.faceunity.encoder.TextureMovieEncoder$VideoThread.run(TextureMovieEncoder.java:468)

**Comment by AndroidInternal** [comment]
非同类问题建议另开isssue。

录制视频的demo有，可以试试切换到其他分支看看效果。

这个错误像是一个texture类型不匹配的问题。

**Comment by zhonglikui** [comment]
将armeabi-v7a的so放至armeabi对应文件夹,解决了使用问题，但是app在上传Google Play后提示应用与设备不兼容，是否能够提供一份armeabi的.so库让我来试一下能否解决这个问题！我使用的是beta分支。

**Comment by AndroidInternal** [comment]
fixed Google Play's filter issue in https://github.com/Faceunity/FULiveDemoDroid/commit/c7dbfd0957ab707cd9ca69349d7272f4fcad351e

**Comment by AndroidInternal** [comment]
谢谢反馈
